"""
Bloem-style Universal Pretraining with LSTM Source Generator

This implements the key insight from Peter Bloem's "Universal pre-training by 
iterated random computation": train a target model on sequences generated by 
randomly-initialized source models.

The randomly-initialized LSTM generates diverse, structured sequences that span
the space of computable patterns—approximating Solomonoff's universal prior.

Usage:
    python train_bloem_source.py --target lstm --epochs 100 --buffer_size 10000
    python train_bloem_source.py --target transformer --epochs 100 --use_antisol
"""

import argparse
import json
import math
import random
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm, trange

# Import our existing models
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from torch_models.lstm import LSTMConfig, LSTMDecoderLM
from torch_models.transformer import TransformerConfig, TransformerDecoderLM


@dataclass
class BloemSourceConfig:
    """Configuration for Bloem-style LSTM source generator."""
    emb: int = 128
    num_layers: int = 2
    num_tokens: int = 256
    weight_mult_range: Tuple[float, float] = (1.0, 3.5)
    emb_mult: float = 1e-8  # Small embedding weight for predictable chaos transition
    temperature: float = 0.5
    

class LSTMSourceGenerator(nn.Module):
    """
    LSTM-based source generator for universal pretraining.
    
    Key difference from standard LSTM: weights are re-initialized randomly
    for each batch, creating diverse structured sequences.
    """
    
    def __init__(self, config: BloemSourceConfig):
        super().__init__()
        self.config = config
        
        self.token_embedding = nn.Embedding(
            num_embeddings=config.num_tokens,
            embedding_dim=config.emb
        )
        self.lstm = nn.LSTM(
            input_size=config.emb,
            hidden_size=config.emb,
            num_layers=config.num_layers,
            batch_first=True
        )
        self.to_logits = nn.Linear(config.emb, config.num_tokens)
        
    def reset_and_scale(self, weight_mult: float):
        """Reset parameters and scale LSTM weights for controlled chaos."""
        self.token_embedding.reset_parameters()
        self.lstm.reset_parameters()
        self.to_logits.reset_parameters()
        
        # Scale LSTM weights
        for name, param in self.lstm.named_parameters():
            if 'weight' in name:
                param.data *= weight_mult
                
        # Very small embedding weights for predictable transition to chaos
        self.token_embedding.weight.data *= self.config.emb_mult
        
    def forward(self, x: torch.Tensor, hidden: Optional[Tuple] = None):
        """Forward pass."""
        emb = self.token_embedding(x)
        out, hidden = self.lstm(emb, hidden)
        logits = self.to_logits(out)
        return logits, hidden
    
    @torch.no_grad()
    def sample_sequence(
        self,
        seed: torch.Tensor,
        length: int,
        temperature: float = 0.5,
        conditional: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        """
        Autoregressively sample a sequence.
        
        Args:
            seed: Initial tokens (batch_size, seed_len)
            length: Total sequence length to generate
            temperature: Sampling temperature
            conditional: Optional conditioning sequence to mix with
            
        Returns:
            Generated sequence (batch_size, length)
        """
        batch_size, seed_len = seed.shape
        device = seed.device
        
        sequence = seed.clone()
        hidden = None
        
        for i in range(length - seed_len):
            # Get logits for last token
            logits, hidden = self.forward(sequence[:, -1:], hidden)
            logits = logits[:, -1, :] / temperature
            
            # Sample
            probs = F.softmax(logits, dim=-1)
            next_token = torch.multinomial(probs, num_samples=1)
            
            # Optionally mix with conditional
            if conditional is not None and i + seed_len < conditional.shape[1]:
                # With some probability, use the conditional token instead
                mask = torch.rand(batch_size, 1, device=device) < 0.3
                next_token = torch.where(mask, conditional[:, i + seed_len:i + seed_len + 1], next_token)
            
            sequence = torch.cat([sequence, next_token], dim=1)
            
        return sequence


class BloemBuffer:
    """
    Buffer for Bloem-style training.
    
    Maintains a buffer of sequences that gets iteratively refined by
    passing through randomly-initialized source models.
    """
    
    def __init__(
        self,
        size: int,
        seq_length: int,
        num_tokens: int,
        device: torch.device
    ):
        self.size = size
        self.seq_length = seq_length
        self.num_tokens = num_tokens
        self.device = device
        
        # Initialize with random sequences
        self.buffer = torch.randint(
            0, num_tokens, (size, seq_length), device=device
        )
        
    def reset_some(self, num_constant: int = 50, num_random: int = 50):
        """Reset some buffer entries to constant/random sequences."""
        # Constant sequences (single token repeated)
        if num_constant > 0:
            idx = random.sample(range(self.size), num_constant)
            tokens = torch.randint(0, self.num_tokens, (num_constant, 1), device=self.device)
            self.buffer[idx] = tokens.expand(-1, self.seq_length)
            
        # Random sequences
        if num_random > 0:
            idx = random.sample(range(self.size), num_random)
            self.buffer[idx] = torch.randint(
                0, self.num_tokens, (num_random, self.seq_length), device=self.device
            )
            
    def update(self, indices: list, new_sequences: torch.Tensor):
        """Update buffer at given indices."""
        self.buffer[indices] = new_sequences
        
    def sample(self, batch_size: int) -> Tuple[torch.Tensor, list]:
        """Sample a batch from the buffer."""
        idx = random.sample(range(self.size), batch_size)
        return self.buffer[idx], idx


def antisol_sample(
    model: nn.Module,
    seeds: torch.Tensor,
    length: int,
    temperature: float = 1.0
) -> torch.Tensor:
    """
    Generate anti-Solomonoff sequences by taking LEAST probable tokens.
    
    These are maximally hard for the model to predict, forcing it to
    learn more general patterns.
    """
    batch_size, seed_len = seeds.shape
    device = seeds.device
    
    sequence = seeds.clone()
    
    with torch.no_grad():
        for _ in range(length - seed_len):
            # Get model predictions
            if hasattr(model, 'forward'):
                logits = model(sequence)
                if isinstance(logits, tuple):
                    logits = logits[0]
            else:
                logits = model(sequence)
                
            # Take LEAST probable token (argmin instead of argmax)
            next_token = logits[:, -1, :].argmin(dim=-1, keepdim=True)
            sequence = torch.cat([sequence, next_token], dim=1)
            
    return sequence


def train_bloem(
    target_model: nn.Module,
    source_config: BloemSourceConfig,
    buffer: BloemBuffer,
    num_batches: int,
    batch_size: int,
    source_batch_size: int,
    learning_rate: float,
    device: torch.device,
    use_antisol: bool = False,
    antisol_ratio: float = 0.1,
    eval_every: int = 500,
    checkpoint_dir: Optional[str] = None,
):
    """
    Main Bloem-style training loop.
    
    Args:
        target_model: Model to train
        source_config: Config for source LSTM generator
        buffer: Training buffer
        num_batches: Number of training batches
        batch_size: Batch size for target model
        source_batch_size: Batch size for source model (updates buffer)
        learning_rate: Learning rate
        device: Device to train on
        use_antisol: Whether to include anti-Solomonoff samples
        antisol_ratio: Ratio of anti-Solomonoff samples in batch
        eval_every: How often to print stats
        checkpoint_dir: Where to save checkpoints
    """
    source = LSTMSourceGenerator(source_config).to(device)
    optimizer = torch.optim.AdamW(target_model.parameters(), lr=learning_rate)
    
    target_model.train()
    losses = []
    
    for batch_idx in trange(num_batches, desc="Training"):
        # === Update buffer with source model outputs ===
        with torch.no_grad():
            # Re-initialize source with random weights
            weight_mult = random.uniform(*source_config.weight_mult_range)
            source.reset_and_scale(weight_mult)
            
            # Sample from buffer and regenerate
            conditional, idx = buffer.sample(source_batch_size)
            
            # Generate new sequences
            seed = torch.randint(
                0, source_config.num_tokens, 
                (source_batch_size, 1), device=device
            )
            new_sequences = source.sample_sequence(
                seed, 
                buffer.seq_length,
                temperature=source_config.temperature,
                conditional=conditional
            )
            
            # Update buffer
            buffer.update(idx, new_sequences)
            
            # Occasionally reset some buffer entries
            if batch_idx % 100 == 0:
                buffer.reset_some(num_constant=50, num_random=50)
        
        # === Train target model on buffer samples ===
        batch, _ = buffer.sample(batch_size)
        
        # Optionally add anti-Solomonoff samples
        if use_antisol and batch_idx > 1000:
            num_antisol = int(batch_size * antisol_ratio)
            if num_antisol > 0:
                antisol_seeds = batch[:num_antisol, :8]  # Short seeds
                antisol_seqs = antisol_sample(
                    target_model, antisol_seeds, buffer.seq_length
                )
                batch = torch.cat([batch[num_antisol:], antisol_seqs], dim=0)
        
        # Next-token prediction loss
        inputs = batch[:, :-1]
        targets = batch[:, 1:]
        
        optimizer.zero_grad()
        logits = target_model(inputs)
        if isinstance(logits, tuple):
            logits = logits[0]
            
        loss = F.cross_entropy(
            logits.reshape(-1, source_config.num_tokens),
            targets.reshape(-1)
        )
        
        loss.backward()
        torch.nn.utils.clip_grad_norm_(target_model.parameters(), 1.0)
        optimizer.step()
        
        losses.append(loss.item())
        
        # === Logging ===
        if batch_idx % eval_every == 0 and batch_idx > 0:
            avg_loss = sum(losses[-eval_every:]) / eval_every
            bpb = avg_loss / math.log(2)  # bits per byte
            print(f"Batch {batch_idx}: loss={avg_loss:.4f}, bpb={bpb:.4f}")
            
        # === Checkpointing ===
        if checkpoint_dir and batch_idx % 10000 == 0 and batch_idx > 0:
            checkpoint_path = Path(checkpoint_dir) / f"bloem_checkpoint_{batch_idx}.pt"
            torch.save({
                'batch_idx': batch_idx,
                'model_state_dict': target_model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'loss': loss.item(),
                'buffer': buffer.buffer,
            }, checkpoint_path)
            print(f"Saved checkpoint to {checkpoint_path}")
            
    return losses


def main():
    parser = argparse.ArgumentParser(description="Bloem-style Universal Pretraining")
    
    # Target model
    parser.add_argument("--target", type=str, default="lstm", choices=["lstm", "transformer"])
    parser.add_argument("--target_emb", type=int, default=256)
    parser.add_argument("--target_layers", type=int, default=2)
    parser.add_argument("--target_heads", type=int, default=8)  # For transformer
    
    # Source model
    parser.add_argument("--source_emb", type=int, default=128)
    parser.add_argument("--source_layers", type=int, default=2)
    parser.add_argument("--weight_mult_min", type=float, default=1.0)
    parser.add_argument("--weight_mult_max", type=float, default=3.5)
    
    # Training
    parser.add_argument("--num_batches", type=int, default=100000)
    parser.add_argument("--batch_size", type=int, default=64)
    parser.add_argument("--source_batch_size", type=int, default=128)
    parser.add_argument("--buffer_size", type=int, default=10000)
    parser.add_argument("--seq_length", type=int, default=256)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--num_tokens", type=int, default=256)
    
    # Anti-Solomonoff
    parser.add_argument("--use_antisol", action="store_true")
    parser.add_argument("--antisol_ratio", type=float, default=0.1)
    
    # Output
    parser.add_argument("--checkpoint_dir", type=str, default=None,
                        help="Checkpoint directory (default: ./checkpoints/bloem_{target}_{timestamp})")
    parser.add_argument("--eval_every", type=int, default=500)
    
    args = parser.parse_args()
    
    # Generate experiment-specific checkpoint directory if not provided
    if args.checkpoint_dir is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        args.checkpoint_dir = f"./checkpoints/bloem_{args.target}_{timestamp}"
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    print(f"Checkpoint dir: {args.checkpoint_dir}")
    
    # Create target model
    if args.target == "lstm":
        config = LSTMConfig(
            vocab_size=args.num_tokens,
            embedding_dim=args.target_emb,
            hidden_dim=args.target_emb,
            num_layers=args.target_layers,
        )
        target_model = LSTMDecoderLM(config).to(device)
    else:
        config = TransformerConfig(
            vocab_size=args.num_tokens,
            embedding_dim=args.target_emb,
            num_layers=args.target_layers,
            num_heads=args.target_heads,
        )
        target_model = TransformerDecoderLM(config).to(device)
        
    print(f"Target model: {args.target}")
    print(f"Parameters: {sum(p.numel() for p in target_model.parameters()):,}")
    
    # Create source config
    source_config = BloemSourceConfig(
        emb=args.source_emb,
        num_layers=args.source_layers,
        num_tokens=args.num_tokens,
        weight_mult_range=(args.weight_mult_min, args.weight_mult_max),
    )
    
    # Create buffer
    buffer = BloemBuffer(
        size=args.buffer_size,
        seq_length=args.seq_length,
        num_tokens=args.num_tokens,
        device=device,
    )
    
    # Create checkpoint directory
    if args.checkpoint_dir:
        Path(args.checkpoint_dir).mkdir(parents=True, exist_ok=True)
        
    # Save config
    config_path = Path(args.checkpoint_dir) / "config.json"
    with open(config_path, "w") as f:
        json.dump(vars(args), f, indent=2)
    
    # Train
    losses = train_bloem(
        target_model=target_model,
        source_config=source_config,
        buffer=buffer,
        num_batches=args.num_batches,
        batch_size=args.batch_size,
        source_batch_size=args.source_batch_size,
        learning_rate=args.lr,
        device=device,
        use_antisol=args.use_antisol,
        antisol_ratio=args.antisol_ratio,
        eval_every=args.eval_every,
        checkpoint_dir=args.checkpoint_dir,
    )
    
    # Save final model
    final_path = Path(args.checkpoint_dir) / "bloem_final.pt"
    torch.save({
        'model_state_dict': target_model.state_dict(),
        'config': vars(args),
        'losses': losses,
    }, final_path)
    print(f"Saved final model to {final_path}")


if __name__ == "__main__":
    main()
